apiVersion: apps/v1
kind: Deployment
metadata:
  name: whale-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whale-db
  template:
    metadata:
      labels:
        app: whale-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: whale_tracker
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: whale-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP # เปิดให้คุยได้แค่ภายในคลัสเตอร์เท่านั้น